CREATE TABLE [Staging].[OBWP_JailMatch] (
    [ID]                        INT              NOT NULL IDENTITY (1, 1) PRIMARY KEY,
    [SysInsertUser]             VARCHAR (50)     NULL,
    [SysInsertDate]             DATETIME         NOT NULL DEFAULT getdate(),
    [HashSignature]             VARBINARY (8000) NULL,
    [ResidenceCountyCode]       CHAR (2)         NOT NULL DEFAULT '18', 
    [SocSecNo]                  CHAR (9)         NULL,
    [ApplicantStatusCode]       VARCHAR (50)     NULL,
    [FirstName]                 VARCHAR (50)     NULL,
    [LastName]                  VARCHAR (50)     NULL,
    [GenderCode]                VARCHAR (50)     NULL,
    [BirthDate]                 DATE             NULL,
    [Age]                       INT              NULL,
    [CaseSerialNumber]          VARCHAR (50)     NULL,
    [ProgramCode]               VARCHAR (50)     NULL,
    [CaseWorkerNumber]          VARCHAR (50)     NULL,
    [BDAAidBeginDate]           DATE             NULL,
    [AidCodeEndDate]            DATE             NULL,
    [ApplicantID]               VARCHAR (50)     NULL,
    [BillingNumber]             VARCHAR (50)     NULL,
    [LivingArrangementTypeCode] VARCHAR (50)     NULL,
    [IsValid]                   BIT              NOT NULL DEFAULT 1, 
    [IsLoaded]                  BIT              NOT NULL DEFAULT 0, 
    [LoadDate]                  DATETIME         NOT NULL DEFAULT '1900-01-01',
    [Comments]                  VARCHAR (1024)   NULL
);

