CREATE TABLE [Staging].[OBWP_JailMatch] (
    [ID]                        INT              IDENTITY (1, 1) NOT NULL,
    [SysInsertUser]             VARCHAR (50)     CONSTRAINT [DF_OBWP_JailMatch_SysInsertUser] DEFAULT ('System') NOT NULL,
    [SysInsertDate]             DATETIME         CONSTRAINT [DF_OBWP_JailMatch_SysInsertDate] DEFAULT (getdate()) NOT NULL,
    [HashSignature]             VARBINARY (8000) NULL,
    [ResidenceCountyCode]       CHAR (2)         CONSTRAINT [DF_OBWP_JailMatch_ResidenceCountyCode] DEFAULT ('2') NOT NULL,
    [SocSecNo]                  CHAR (9)         NULL,
    [ApplicantStatusCode]       VARCHAR (50)     NULL,
    [FirstName]                 VARCHAR (50)     NULL,
    [LastName]                  VARCHAR (50)     NULL,
    [GenderCode]                VARCHAR (50)     NULL,
    [BirthDate]                 DATE             NULL,
    [Age]                       INT              NULL,
    [CaseSerialNumber]          VARCHAR (50)     NULL,
    [ProgramCode]               VARCHAR (50)     NULL,
    [CaseWorkerNumber]          VARCHAR (50)     NULL,
    [BDAAidBeginDate]           DATE             NULL,
    [AidCodeEndDate]            DATE             NULL,
    [ApplicantID]               VARCHAR (50)     NULL,
    [BillingNumber]             VARCHAR (50)     NULL,
    [LivingArrangementTypeCode] VARCHAR (50)     NULL,
    [IsValid]                   BIT              CONSTRAINT [DF_OBWP_JailMatch_IsValid] DEFAULT ((1)) NOT NULL,
    [IsLoaded]                  BIT              CONSTRAINT [DF_OBWP_JailMatch_IsLoaded] DEFAULT ((0)) NOT NULL,
    [LoadDate]                  DATETIME         CONSTRAINT [DF_OBWP_JailMatch_LoadDate] DEFAULT ('1900-01-01') NOT NULL,
    [Comments]                  VARCHAR (1024)   NULL
);

