USE SACWISCUY
GO

DELETE FROM SACWISCUY.DBO.PROVIDER_CHARACTERISTICS
WHERE PROVIDER_CHAR_ID IN
(SELECT *
FROM OPENQUERY(ADHOC_SACRPT,'
SELECT 
	PROVIDER_CHAR_ID
FROM SACWIS.PROVIDER_CHARACTERISTICS
WHERE MODIFIED_DATE >= SYSDATE - 7
'))

INSERT INTO SACWISCUY.DBO.PROVIDER_CHARACTERISTICS
SELECT 
PROVIDER_CHAR_ID
, PROVIDER_TYPE_CODE
, EFFECTIVE_DATE
, END_DATE
, STATUS_CODE
, PROVIDER_ID
, CREATED_BY
, CREATED_DATE
, MODIFIED_BY
, MODIFIED_DATE
, APP_VERSION_NBR

FROM OPENQUERY(ADHOC_SACRPT,'
SELECT
PROVIDER_CHAR_ID
, PROVIDER_TYPE_CODE
, EFFECTIVE_DATE
, END_DATE
, STATUS_CODE
, PROVIDER_ID
, CREATED_BY
, CREATED_DATE
, MODIFIED_BY
, MODIFIED_DATE
, APP_VERSION_NBR

FROM SACWIS.PROVIDER_CHARACTERISTICS
WHERE MODIFIED_DATE >= SYSDATE - 7
')