USE SACWISCUY
GO

DELETE FROM SACWISCUY.DBO.CASE_CATEGORY
WHERE CASE_CATEGORY_ID IN
(SELECT *
FROM OPENQUERY(ADHOC_SACRPT,'
SELECT 
	CASE_CATEGORY_ID
FROM SACWIS.CASE_CATEGORY
WHERE MODIFIED_DATE >= SYSDATE - 7
'))

INSERT INTO SACWISCUY.DBO.CASE_CATEGORY
SELECT 
  CASE_CATEGORY_ID 
, CASE_ID 
, CASE_CATEGORY_CODE 
, BEGIN_EFF_DATE 
, END_EFF_DATE 
, CREATED_BY 
, CREATED_DATE 
, MODIFIED_BY 
, MODIFIED_DATE 
, AR_PATHWAY_SWITCH 
, APP_VERSION_NBR 

FROM OPENQUERY(ADHOC_SACRPT,'
SELECT 
  CASE_CATEGORY_ID 
, CASE_ID 
, CASE_CATEGORY_CODE 
, BEGIN_EFF_DATE 
, END_EFF_DATE 
, CREATED_BY 
, CREATED_DATE 
, MODIFIED_BY 
, MODIFIED_DATE 
, AR_PATHWAY_SWITCH 
, APP_VERSION_NBR 
FROM SACWIS.CASE_CATEGORY
WHERE MODIFIED_DATE >= SYSDATE - 7
')