USE SACWISCUY
GO

DELETE FROM SACWISCUY.DBO.PLACEMENT_SETTING
WHERE PLACEMENT_SETTING_ID IN
(SELECT *
FROM OPENQUERY(ADHOC_SACRPT,'
SELECT 
	PLACEMENT_SETTING_ID
FROM SACWIS.PLACEMENT_SETTING
WHERE MODIFIED_DATE >= SYSDATE - 7
'))

INSERT INTO SACWISCUY.DBO.PLACEMENT_SETTING
SELECT 
PLACEMENT_EPISODE_ID
, PLACEMENT_REQUEST_ID
, PLACEMENT_SETTING_ID
, ADDITIONAL_COMMENT_TEXT
, AFTERHOURS_PLACEMENT_FLAG
, BEGIN_DATE
, EMERGENCY_PLACEMENT_FLAG
, END_CIRCUMSTANCE_TEXT
, END_DATE, END_REASON_CODE
, ESTIMATED_END_DATE
, ICCA_DELIVERED_DATE
, ICPC_PLACEMENT_FLAG
, ICWA_PLACEMENT_FLAG
, MAINTAIN_PLACEMENT_EFFORT_CODE
, MAINTAIN_PLACEMENT_EFFORT_TEXT
, NON_CONFORMING_PLACEMENT_FLAG
, NON_CONFORMING_REASON_CODE
, PLACEMENT_TYPE_CODE
, PROVIDER_RELATIONSHIP_CODE
, RCNO_CONSIDERED_FLAG
, SECONDARY_END_REASON_CODE
, STATUS_CODE
, CHILD_ID
, AGENCY_ID
, SERVICE_PROVIDER_ID
, SERVICE_ID
, GROUP_CAT_ID
, CREATED_BY
, CREATED_DATE
, MODIFIED_BY
, MODIFIED_DATE
, PAYMENT_PROVIDER_ID
, PAYMENT_SERVICE_ID
, APP_VERSION_NBR

FROM OPENQUERY(ADHOC_SACRPT,'
SELECT 
PLACEMENT_EPISODE_ID
, PLACEMENT_REQUEST_ID
, PLACEMENT_SETTING_ID
, ADDITIONAL_COMMENT_TEXT
, AFTERHOURS_PLACEMENT_FLAG
, BEGIN_DATE
, EMERGENCY_PLACEMENT_FLAG
, END_CIRCUMSTANCE_TEXT
, END_DATE, END_REASON_CODE
, ESTIMATED_END_DATE
, ICCA_DELIVERED_DATE
, ICPC_PLACEMENT_FLAG
, ICWA_PLACEMENT_FLAG
, MAINTAIN_PLACEMENT_EFFORT_CODE
, MAINTAIN_PLACEMENT_EFFORT_TEXT
, NON_CONFORMING_PLACEMENT_FLAG
, NON_CONFORMING_REASON_CODE
, PLACEMENT_TYPE_CODE
, PROVIDER_RELATIONSHIP_CODE
, RCNO_CONSIDERED_FLAG
, SECONDARY_END_REASON_CODE
, STATUS_CODE
, CHILD_ID
, AGENCY_ID
, SERVICE_PROVIDER_ID
, SERVICE_ID
, GROUP_CAT_ID
, CREATED_BY
, CREATED_DATE
, MODIFIED_BY
, MODIFIED_DATE
, PAYMENT_PROVIDER_ID
, PAYMENT_SERVICE_ID
, APP_VERSION_NBR
FROM SACWIS.PLACEMENT_SETTING
WHERE MODIFIED_DATE >= SYSDATE - 7
')