USE SACWISCUY
GO

DELETE FROM SACWISCUY.DBO.CASE_STATUS
WHERE CASE_STATUS_ID IN
(SELECT *
FROM OPENQUERY(ADHOC_SACRPT,'
SELECT 
	CASE_STATUS_ID
FROM SACWIS.CASE_STATUS
WHERE MODIFIED_DATE >= SYSDATE - 7
'))

INSERT INTO SACWISCUY.DBO.CASE_STATUS
SELECT 
CASE_STATUS_ID
, CASE_ID
, CASE_STATUS_CODE
, BEGIN_EFF_DATE
, END_EFF_DATE
, CREATED_BY
, CREATED_DATE
, MODIFIED_BY
, MODIFIED_DATE
, SUNSET_DATE
, SUNSET_ACTIVITY_CODE
, APP_VERSION_NBR

FROM OPENQUERY(ADHOC_SACRPT,'
SELECT 
CASE_STATUS_ID
, CASE_ID
, CASE_STATUS_CODE
, BEGIN_EFF_DATE
, END_EFF_DATE
, CREATED_BY
, CREATED_DATE
, MODIFIED_BY
, MODIFIED_DATE
, SUNSET_DATE
, SUNSET_ACTIVITY_CODE
, APP_VERSION_NBR
FROM SACWIS.CASE_STATUS
WHERE MODIFIED_DATE >= SYSDATE - 7
')