USE SACWISCUY
GO

DELETE FROM SACWISCUY.DBO.SERVICE_TYPE
WHERE SERVICE_ID IN
(SELECT *
FROM OPENQUERY(ADHOC_SACRPT,'
SELECT 
	SERVICE_ID
FROM SACWIS.SERVICE_TYPE
WHERE MODIFIED_DATE >= SYSDATE - 7
'))

INSERT INTO SACWISCUY.DBO.SERVICE_TYPE
SELECT 
SERVICE_ID
, AGENCY_ID
, SERVICE_DESC
, SERVICE_LONG_DESC
, OBSOLETE_DATE
, UNPAID_SVC_FLAG
, PRE_PAID_PAY_FLAG
, PLACEMENT_SRV_FLAG
, PROSPECTIVE_PAY_FLAG
, GROUP_CAT_ID
, CREATED_BY
, CREATED_DATE
, LEAVE_DAYS_TO_BE_PAID
, MODIFIED_BY
, MODIFIED_DATE
, FUND_SOURCE_DESC
, APP_VERSION_NBR

FROM OPENQUERY(ADHOC_SACRPT,'
SELECT
SERVICE_ID
, AGENCY_ID
, SERVICE_DESC
, SERVICE_LONG_DESC
, OBSOLETE_DATE
, UNPAID_SVC_FLAG
, PRE_PAID_PAY_FLAG
, PLACEMENT_SRV_FLAG
, PROSPECTIVE_PAY_FLAG
, GROUP_CAT_ID
, CREATED_BY
, CREATED_DATE
, LEAVE_DAYS_TO_BE_PAID
, MODIFIED_BY
, MODIFIED_DATE
, FUND_SOURCE_DESC
, APP_VERSION_NBR

FROM SACWIS.SERVICE_TYPE
WHERE MODIFIED_DATE >= SYSDATE - 7
')