USE SACWISCUY

DELETE FROM SACWISCUY.DBO.CASE_BASE
WHERE CASE_ID IN
(SELECT *
FROM OPENQUERY(ADHOC_SACRPT,'
SELECT 
	CASE_ID
FROM SACWIS.CASE_BASE
WHERE MODIFIED_DATE >= SYSDATE - 7
'))



INSERT INTO SACWISCUY.DBO.CASE_BASE
SELECT 
CASE_ID
, FIRST_NAME
, MIDDLE_NAME
, LAST_NAME
, PRIMARY_CARETAKER_CODE
, SECONDARY_CARETAKER_CODE
, CLOSED_CASE_ADDRESS_ID
, CREATED_BY
, CREATED_DATE
, MODIFIED_BY
, MODIFIED_DATE
, ISADOPTIONCASE_FLAG
, ORIGINAL_CASE_ID
, RESTRICTED_FLAG
, RESTRICTED_BY_EMPLOYEE_ID
, RESTRICTED_COMMENTS_TEXT
, RESTRICTED_DATE
, APP_VERSION_NBR

FROM OPENQUERY(ADHOC_SACRPT,'
SELECT 
CASE_ID
, FIRST_NAME
, MIDDLE_NAME
, LAST_NAME
, PRIMARY_CARETAKER_CODE
, SECONDARY_CARETAKER_CODE
, CLOSED_CASE_ADDRESS_ID
, CREATED_BY
, CREATED_DATE
, MODIFIED_BY
, MODIFIED_DATE
, ISADOPTIONCASE_FLAG
, ORIGINAL_CASE_ID
, RESTRICTED_FLAG
, RESTRICTED_BY_EMPLOYEE_ID
, RESTRICTED_COMMENTS_TEXT
, RESTRICTED_DATE
, APP_VERSION_NBR
FROM SACWIS.CASE_BASE
WHERE MODIFIED_DATE >= SYSDATE - 7
')