USE SACWISCUY
GO

DELETE FROM SACWISCUY.DBO.PROVIDER_PLACEMENT_CRITERIA
WHERE PROVIDER_PLCMNT_CRITERIA_ID IN
(SELECT *
FROM OPENQUERY(ADHOC_SACRPT,'
SELECT 
	PROVIDER_PLCMNT_CRITERIA_ID
FROM SACWIS.PROVIDER_PLACEMENT_CRITERIA
WHERE MODIFIED_DATE >= SYSDATE - 7
'))

INSERT INTO SACWISCUY.DBO.PROVIDER_PLACEMENT_CRITERIA
SELECT 
PROVIDER_PLCMNT_CRITERIA_ID
, PROVIDER_TYPE_CODE
, EFFECTIVE_DATE
, END_DATE
, STATUS_CODE
, PROVIDER_ID
, CREATED_BY
, CREATED_DATE
, MODIFIED_BY
, MODIFIED_DATE
, TOTAL_NUMBER_OF_CHILDREN
, APP_VERSION_NBR

FROM OPENQUERY(ADHOC_SACRPT,'
SELECT 
PROVIDER_PLCMNT_CRITERIA_ID
, PROVIDER_TYPE_CODE
, EFFECTIVE_DATE
, END_DATE
, STATUS_CODE
, PROVIDER_ID
, CREATED_BY
, CREATED_DATE
, MODIFIED_BY
, MODIFIED_DATE
, TOTAL_NUMBER_OF_CHILDREN
, APP_VERSION_NBR
FROM SACWIS.PROVIDER_PLACEMENT_CRITERIA
WHERE MODIFIED_DATE >= SYSDATE - 7 
')