USE SACWISCUY
GO

DELETE FROM SACWISCUY.DBO.CASE_AGENCY_LINK
WHERE CASE_AGENCY_LINK_ID IN
(SELECT *
FROM OPENQUERY(ADHOC_SACRPT,'
SELECT 
	CASE_AGENCY_LINK_ID
FROM SACWIS.CASE_AGENCY_LINK
WHERE MODIFIED_DATE >= SYSDATE - 7
'))

INSERT INTO SACWISCUY.DBO.CASE_AGENCY_LINK
SELECT 
CASE_AGENCY_LINK_ID
, CASE_ID
, LOCAL_AGENCY_ID
, BEGIN_EFF_DATE
, END_EFF_DATE
, CREATED_BY
, CREATED_DATE
, MODIFIED_BY
, MODIFIED_DATE
, APP_VERSION_NBR

FROM OPENQUERY(ADHOC_SACRPT,'
SELECT 
CASE_AGENCY_LINK_ID
, CASE_ID
, LOCAL_AGENCY_ID
, BEGIN_EFF_DATE
, END_EFF_DATE
, CREATED_BY
, CREATED_DATE
, MODIFIED_BY
, MODIFIED_DATE
, APP_VERSION_NBR
FROM SACWIS.CASE_AGENCY_LINK
WHERE MODIFIED_DATE >= SYSDATE - 7
')