USE SACWISCUY
GO

DELETE FROM SACWISCUY.DBO.PROVIDER_CHAR_DETAIL
WHERE PROVIDER_CHAR_DETAIL_ID IN
(SELECT *
FROM OPENQUERY(ADHOC_SACRPT,'
SELECT 
	PROVIDER_CHAR_DETAIL_ID
FROM SACWIS.PROVIDER_CHAR_DETAIL
WHERE MODIFIED_DATE >= SYSDATE - 7
'))

INSERT INTO SACWISCUY.DBO.PROVIDER_CHAR_DETAIL
SELECT 
PROVIDER_CHAR_DETAIL_ID
, CHARACTERISTIC_CODE
, WILLING_TO_CONSIDER_CODE
, PROVIDER_CHAR_ID
, CREATED_BY
, CREATED_DATE
, MODIFIED_BY
, MODIFIED_DATE
, APP_VERSION_NBR

FROM OPENQUERY(ADHOC_SACRPT,'
SELECT 
PROVIDER_CHAR_DETAIL_ID
, CHARACTERISTIC_CODE
, WILLING_TO_CONSIDER_CODE
, PROVIDER_CHAR_ID
, CREATED_BY
, CREATED_DATE
, MODIFIED_BY
, MODIFIED_DATE
, APP_VERSION_NBR
FROM SACWIS.PROVIDER_CHAR_DETAIL
WHERE MODIFIED_DATE >= SYSDATE - 7
')