USE SACWISCUY
GO

DELETE FROM SACWISCUY.DBO.PROVIDER_TYPE
WHERE PROVIDER_TYPE_ID IN
(SELECT *
FROM OPENQUERY(ADHOC_SACRPT,'
SELECT 
	PROVIDER_TYPE_ID
FROM SACWIS.PROVIDER_TYPE
WHERE MODIFIED_DATE >= SYSDATE - 7
'))

INSERT INTO SACWISCUY.DBO.PROVIDER_TYPE
SELECT 
PROVIDER_ID
, PROVIDER_TYPE_ID
, TYPE_CODE
, EFFECTIVE_DATE
, END_DATE
, AGENCY_ID
, CURRENT_STATUS_CODE
, CREATED_BY
, CREATED_DATE
, MODIFIED_BY
, MODIFIED_DATE
, APP_VERSION_NBR

FROM OPENQUERY(ADHOC_SACRPT,'
SELECT
PROVIDER_ID
, PROVIDER_TYPE_ID
, TYPE_CODE
, EFFECTIVE_DATE
, END_DATE
, AGENCY_ID
, CURRENT_STATUS_CODE
, CREATED_BY
, CREATED_DATE
, MODIFIED_BY
, MODIFIED_DATE
, APP_VERSION_NBR

FROM SACWIS.PROVIDER_TYPE
WHERE MODIFIED_DATE >= SYSDATE - 7 
')