USE SACWISCUY
GO

DELETE FROM SACWISCUY.DBO.AGENCY_CERTIFICATION
WHERE AGENCY_CERTIFICATION_ID IN
(SELECT *
FROM OPENQUERY(ADHOC_SACRPT,'
SELECT 
	AGENCY_CERTIFICATION_ID
FROM SACWIS.AGENCY_CERTIFICATION
WHERE MODIFIED_DATE >= SYSDATE - 7
'))

INSERT INTO SACWISCUY.DBO.AGENCY_CERTIFICATION
SELECT 
AGENCY_CERTIFICATION_ID
, AGENCY_ID
, CERTIFICATION_STATUS_CODE
, APP_TYPE_CODE
, AMENDMENT_REASON_CODE
, AMENDMENT_DESC
, EFFECTIVE_DATE
, EXPIRATION_DATE
, TEMP_EXPIRATION_DATE
, CREATED_BY
, CREATED_DATE
, MODIFIED_BY
, MODIFIED_DATE
, CERTIFYING_ENTITY_CODE
, CLOSED_DATE, CLOSED_REASON_CODE
, OTHER_REASON_TEXT
, CLOSING_COMMENTS
, SOURCE_AGENCY_CERT_ID
, APP_VERSION_NBR

FROM OPENQUERY(ADHOC_SACRPT,'
SELECT 
AGENCY_CERTIFICATION_ID
, AGENCY_ID
, CERTIFICATION_STATUS_CODE
, APP_TYPE_CODE
, AMENDMENT_REASON_CODE
, AMENDMENT_DESC
, EFFECTIVE_DATE
, EXPIRATION_DATE
, TEMP_EXPIRATION_DATE
, CREATED_BY
, CREATED_DATE
, MODIFIED_BY
, MODIFIED_DATE
, CERTIFYING_ENTITY_CODE
, CLOSED_DATE, CLOSED_REASON_CODE
, OTHER_REASON_TEXT
, CLOSING_COMMENTS
, SOURCE_AGENCY_CERT_ID
, APP_VERSION_NBR
FROM SACWIS.AGENCY_CERTIFICATION
WHERE MODIFIED_DATE >= SYSDATE - 7 
')