USE SACWISCUY
GO

DELETE FROM SACWISCUY.DBO.PROVIDER_LICENSE
WHERE PROVIDER_LICENSE_ID IN
(SELECT *
FROM OPENQUERY(ADHOC_SACRPT,'
SELECT 
	PROVIDER_LICENSE_ID
FROM SACWIS.PROVIDER_LICENSE
WHERE MODIFIED_DATE >= SYSDATE - 7
'))

INSERT INTO SACWISCUY.DBO.PROVIDER_LICENSE
SELECT 
PROVIDER_ID
, PROVIDER_TYPE_ID
, PROVIDER_LICENSE_ID
, CLOSED_REASON_CODE
, LICENSED_LEVEL_OF_CARE_CODE
, LICENSE_EFFECTIVE_DATE
, LICENSE_EXPIRATION_DATE
, LICENSE_STATUS_CODE
, STATUS_EFFECTIVE_DATE
, PROVIDER_NAME_TEXT
, LICENSED_ADDRESS_ID
, CREATED_BY
, CREATED_DATE
, MODIFIED_BY
, MODIFIED_DATE
, CERTIFYING_ENTITY_CODE
, APP_VERSION_NBR

FROM OPENQUERY(ADHOC_SACRPT,'
SELECT
PROVIDER_ID
, PROVIDER_TYPE_ID
, PROVIDER_LICENSE_ID
, CLOSED_REASON_CODE
, LICENSED_LEVEL_OF_CARE_CODE
, LICENSE_EFFECTIVE_DATE
, LICENSE_EXPIRATION_DATE
, LICENSE_STATUS_CODE
, STATUS_EFFECTIVE_DATE
, PROVIDER_NAME_TEXT
, LICENSED_ADDRESS_ID
, CREATED_BY
, CREATED_DATE
, MODIFIED_BY
, MODIFIED_DATE
, CERTIFYING_ENTITY_CODE
, APP_VERSION_NBR

FROM SACWIS.PROVIDER_LICENSE
WHERE MODIFIED_DATE >= SYSDATE - 7
')