USE SACWISCUY
GO

DELETE FROM SACWISCUY.DBO.CASE_PARTICIPANT_RELN
WHERE CASE_PARTICIPANT_RELN_ID IN
(SELECT *
FROM OPENQUERY(ADHOC_SACRPT,'
SELECT 
	CASE_PARTICIPANT_RELN_ID
FROM SACWIS.CASE_PARTICIPANT_RELN
WHERE MODIFIED_DATE >= SYSDATE - 7
'))

INSERT INTO SACWISCUY.DBO.CASE_PARTICIPANT_RELN
SELECT 
CASE_PARTICIPANT_RELN_ID
, CASE_ID, RELATIONSHIP_CODE
, SOURCE_PERSON_ID
, DEST_PERSON_ID
, CREATED_BY
, CREATED_DATE
, MODIFIED_BY
, MODIFIED_DATE
, APP_VERSION_NBR

FROM OPENQUERY(ADHOC_SACRPT,'
SELECT 
CASE_PARTICIPANT_RELN_ID
, CASE_ID, RELATIONSHIP_CODE
, SOURCE_PERSON_ID
, DEST_PERSON_ID
, CREATED_BY
, CREATED_DATE
, MODIFIED_BY
, MODIFIED_DATE
, APP_VERSION_NBR
FROM SACWIS.CASE_PARTICIPANT_RELN
WHERE MODIFIED_DATE >= SYSDATE - 7
')