USE SACWISCUY
GO

DELETE FROM SACWISCUY.DBO.PARTY_ADDRESS
WHERE PARTY_ADDRESS_ID IN
(SELECT *
FROM OPENQUERY(ADHOC_SACRPT,'
SELECT 
	PARTY_ADDRESS_ID
FROM SACWIS.PARTY_ADDRESS
WHERE MODIFIED_DATE >= SYSDATE - 7
'))

INSERT INTO SACWISCUY.DBO.PARTY_ADDRESS
SELECT 
PARTY_ADDRESS_ID
, PARTY_ID, ADDRESS_ID
, PARTY_ADDRESS_TYPE_CODE
, CARE_OF_NAME, DELIVERY_DESC
, PRIMARY_ADDRESS_FLAG
, BEGIN_EFF_DATE
, END_EFF_DATE
, CREATED_BY
, CREATED_DATE
, MODIFIED_BY
, MODIFIED_DATE
, APP_VERSION_NBR

FROM OPENQUERY(ADHOC_SACRPT,'
SELECT 
PARTY_ADDRESS_ID
, PARTY_ID, ADDRESS_ID
, PARTY_ADDRESS_TYPE_CODE
, CARE_OF_NAME, DELIVERY_DESC
, PRIMARY_ADDRESS_FLAG
, TO_CHAR(BEGIN_EFF_DATE) BEGIN_EFF_DATE
, TO_CHAR(END_EFF_DATE) END_EFF_DATE
, CREATED_BY
, TO_CHAR(CREATED_DATE) CREATED_DATE
, MODIFIED_BY
, TO_CHAR(MODIFIED_DATE) MODIFIED_DATE
, APP_VERSION_NBR
FROM SACWIS.PARTY_ADDRESS
WHERE MODIFIED_DATE >= SYSDATE - 7 
')