USE SACWISCUY
GO

DELETE FROM SACWISCUY.DBO.PROVIDER
WHERE PROVIDER_ID IN
(SELECT *
FROM OPENQUERY(ADHOC_SACRPT,'
SELECT 
	PROVIDER_ID
FROM SACWIS.PROVIDER
WHERE MODIFIED_DATE >= SYSDATE - 7
'))

INSERT INTO SACWISCUY.DBO.PROVIDER
SELECT 
PROVIDER_ID
 , PROVIDER_CATEGORY_CODE
 , PARTY_ID, CREATED_BY
 , CREATED_DATE
 , MODIFIED_BY
 , MODIFIED_DATE
 , APP_VERSION_NBR

FROM OPENQUERY(ADHOC_SACRPT,'
SELECT 
PROVIDER_ID
 , PROVIDER_CATEGORY_CODE
 , PARTY_ID, CREATED_BY
 , CREATED_DATE
 , MODIFIED_BY
 , MODIFIED_DATE
 , APP_VERSION_NBR
FROM SACWIS.PROVIDER
WHERE MODIFIED_DATE >= SYSDATE - 7
')