USE SACWISCUY
GO

DELETE FROM SACWISCUY.DBO.PROVIDER_NAME
WHERE PROVIDER_NAME_ID IN
(SELECT *
FROM OPENQUERY(ADHOC_SACRPT,'
SELECT 
	PROVIDER_NAME_ID
FROM SACWIS.PROVIDER_NAME
WHERE MODIFIED_DATE >= SYSDATE - 7
'))

INSERT INTO SACWISCUY.DBO.PROVIDER_NAME
SELECT 
PROVIDER_ID
, PROVIDER_NAME_ID
, NAME_TEXT
, EFFECTIVE_DATE
, END_DATE
, CREATED_BY
, CREATED_DATE
, MODIFIED_BY
, MODIFIED_DATE
, APP_VERSION_NBR

FROM OPENQUERY(ADHOC_SACRPT,'
SELECT
PROVIDER_ID
, PROVIDER_NAME_ID
, NAME_TEXT
, EFFECTIVE_DATE
, END_DATE
, CREATED_BY
, CREATED_DATE
, MODIFIED_BY
, MODIFIED_DATE
, APP_VERSION_NBR

FROM SACWIS.PROVIDER_NAME
WHERE MODIFIED_DATE >= SYSDATE - 7
')