-- there is no modified date column in this table.  the PartialLoad is the same as the full load query for consistency.

USE SACWISCUY
GO

TRUNCATE TABLE AGENCY_CERT_PROVIDER_LINK
GO

INSERT INTO AGENCY_CERT_PROVIDER_LINK
SELECT 
AGENCY_CERTIFICATION_ID
, PROVIDER_ID
, AGENCY_CERT_PRVDR_LNK_ID
, CONVERTED_DATA
, TRANSFER_AGENCY_CERT_ID
, TRANSFER_AGENCY_CERT_TYPE_CODE
, APP_VERSION_NBR

FROM OPENQUERY(ADHOC_SACRPT,'
SELECT 
AGENCY_CERTIFICATION_ID
, PROVIDER_ID
, AGENCY_CERT_PRVDR_LNK_ID
, CONVERTED_DATA
, TRANSFER_AGENCY_CERT_ID
, TRANSFER_AGENCY_CERT_TYPE_CODE
, APP_VERSION_NBR
FROM SACWIS.AGENCY_CERT_PROVIDER_LINK
-- WHERE 
')