USE SACWISCUY
GO

DELETE FROM SACWISCUY.DBO.[CONTRACT]
WHERE CONTRACT_ID IN
(SELECT *
FROM OPENQUERY(ADHOC_SACRPT,'
SELECT 
	CONTRACT_ID
FROM SACWIS.CONTRACT
WHERE MODIFIED_DATE >= SYSDATE - 7
'))

INSERT INTO SACWISCUY.DBO.[CONTRACT]
SELECT 
CONTRACT_ID
, AGENCY_ID
, PROVIDER_ID
, CONTRACT_NBR
, VENDOR_NBR
, CONTRACT_TYPE_CODE
, CONTRACT_STATUS_CODE
, CONTRACT_BEGIN_DATE
, CONTRACT_END_DATE
, CONTRACT_AMOUNT
, ENCUMBERED_AMOUNT
, CONTRACT_APPROVAL_DATE
, CONTRACT_ENCUMBERED_DATE
, NOTIFICATION_TYPE_CODE
, NOTIFICATION_CEILING_TYPE_CODE
, COMMENT_TEXT
, CREATED_BY
, CREATED_DATE
, MODIFIED_BY
, MODIFIED_DATE
, ORIG_CONTRACT_BEGIN_DATE
, ORIG_CONTRACT_END_DATE
, ORIG_CONTRACT_AMOUNT
, ORIG_CONTRACT_ID
, PAID_LEAVE_DAYS
, APP_VERSION_NBR

FROM OPENQUERY(ADHOC_SACRPT,'
SELECT 
CONTRACT_ID
, AGENCY_ID
, PROVIDER_ID
, CONTRACT_NBR
, VENDOR_NBR
, CONTRACT_TYPE_CODE
, CONTRACT_STATUS_CODE
, CONTRACT_BEGIN_DATE
, CONTRACT_END_DATE
, CONTRACT_AMOUNT
, ENCUMBERED_AMOUNT
, CONTRACT_APPROVAL_DATE
, CONTRACT_ENCUMBERED_DATE
, NOTIFICATION_TYPE_CODE
, NOTIFICATION_CEILING_TYPE_CODE
, COMMENT_TEXT
, CREATED_BY
, CREATED_DATE
, MODIFIED_BY
, MODIFIED_DATE
, ORIG_CONTRACT_BEGIN_DATE
, ORIG_CONTRACT_END_DATE
, ORIG_CONTRACT_AMOUNT
, ORIG_CONTRACT_ID
, PAID_LEAVE_DAYS
, APP_VERSION_NBR
FROM SACWIS.CONTRACT
WHERE MODIFIED_DATE >= SYSDATE - 7
')