use SacwisCuy
go

truncate table Party_Address
go

insert into Party_Address
select 
PARTY_ADDRESS_ID
, PARTY_ID, ADDRESS_ID
, PARTY_ADDRESS_TYPE_CODE
, CARE_OF_NAME, DELIVERY_DESC
, PRIMARY_ADDRESS_FLAG
, BEGIN_EFF_DATE
, END_EFF_DATE
, CREATED_BY
, CREATED_DATE
, MODIFIED_BY
, MODIFIED_DATE
, APP_VERSION_NBR

from openquery(adhoc_sacrpt,'
select 
PARTY_ADDRESS_ID
, PARTY_ID, ADDRESS_ID
, PARTY_ADDRESS_TYPE_CODE
, CARE_OF_NAME, DELIVERY_DESC
, PRIMARY_ADDRESS_FLAG
, to_char(BEGIN_EFF_DATE) BEGIN_EFF_DATE
, to_char(END_EFF_DATE) END_EFF_DATE
, CREATED_BY
, to_char(CREATED_DATE) CREATED_DATE
, MODIFIED_BY
, to_char(MODIFIED_DATE) MODIFIED_DATE
, APP_VERSION_NBR
from sacwis.Party_Address
-- where 
')