use SacwisCuy
go

truncate table Provider_Status
go

insert into Provider_Status
select 
PROVIDER_ID
, PROVIDER_STATUS_ID
, STATUS_CODE
, EFFECTIVE_DATE
, REVIEW_DATE
, REASON_CODE
, OTHER_REASON_TEXT
, COMMENT_TEXT
, RESOLVED_FLAG
, CREATED_BY
, CREATED_DATE
, MODIFIED_BY
, MODIFIED_DATE
, RESOLVED_DATE
, APP_VERSION_NBR

from openquery(adhoc_sacrpt,'
select
PROVIDER_ID
, PROVIDER_STATUS_ID
, STATUS_CODE
, EFFECTIVE_DATE
, REVIEW_DATE
, REASON_CODE
, OTHER_REASON_TEXT
, COMMENT_TEXT
, RESOLVED_FLAG
, CREATED_BY
, CREATED_DATE
, MODIFIED_BY
, MODIFIED_DATE
, RESOLVED_DATE
, APP_VERSION_NBR

from sacwis.Provider_Status
-- where 
')