use SacwisCuy
go

truncate table Address
go

insert into ADDRESS
select 
ADDRESS_ID
, DOMESTIC_FOREIGN_FLAG
, STREET_NBR
, PRE_DIRECTIONAL_CODE
, STREET_NAME
, STREET_SUFFIX_CODE
, POST_DIRECTIONAL_CODE
, UNIT_NAME_CODE
, UNIT_NBR
, NEIGHBORHOOD_NAME
, CITY_NAME
, COUNTY_CODE
, OTHER_COUNTY_NAME
, STATE_CODE
, ZIP5_CODE
, ZIP4_CODE
, DIRECTIONS
, SCHOOL_DISTRICT_CODE
, OTHER_SCHOOL_DISTRICT_NAME
, JURISDICTION_CODE
, OTHER_JURISDICTION_NAME
, GEO_CODE, CENSUS_TRACT
, VALID_ADDRESS_FLAG
, FOREIGN_ADDRESS_LINE1
, FOREIGN_ADDRESS_LINE2
, FOREIGN_ADDRESS_LINE3
, ENV_HAZARD_FLAG
, ENV_HAZARD_DESC
, CREATED_BY
, CREATED_DATE
, MODIFIED_BY
, MODIFIED_DATE
, SETS_MODIFIED_DATE
, APP_VERSION_NBR
, UNKNOWN_ADDRESS_FLAG
, FULL_STREET_NAME
, LATITUDE
, LONGITUDE 


 from openquery(adhoc_sacrpt,'
 select 
 ADDRESS_ID
, DOMESTIC_FOREIGN_FLAG
, STREET_NBR
, PRE_DIRECTIONAL_CODE
, STREET_NAME
, STREET_SUFFIX_CODE
, POST_DIRECTIONAL_CODE
, UNIT_NAME_CODE
, UNIT_NBR
, NEIGHBORHOOD_NAME
, CITY_NAME
, COUNTY_CODE
, OTHER_COUNTY_NAME
, STATE_CODE
, ZIP5_CODE
, ZIP4_CODE
, DIRECTIONS
, SCHOOL_DISTRICT_CODE
, OTHER_SCHOOL_DISTRICT_NAME
, JURISDICTION_CODE
, OTHER_JURISDICTION_NAME
, GEO_CODE, CENSUS_TRACT
, VALID_ADDRESS_FLAG
, FOREIGN_ADDRESS_LINE1
, FOREIGN_ADDRESS_LINE2
, FOREIGN_ADDRESS_LINE3
, ENV_HAZARD_FLAG
, ENV_HAZARD_DESC
, CREATED_BY
, CREATED_DATE
, MODIFIED_BY
, MODIFIED_DATE
, SETS_MODIFIED_DATE
, APP_VERSION_NBR
, UNKNOWN_ADDRESS_FLAG
, FULL_STREET_NAME
, LATITUDE
, LONGITUDE 
from sacwis.address
-- where latitude is not null')