use SacwisCuy
go

truncate table Placement_Leave
go

insert into Placement_Leave
select 
PLACEMENT_SETTING_ID
, PLACEMENT_LEAVE_ID
, ESTIMATED_RETURN_DATE
, LEAVE_DATE
, LEAVE_TYPE_CODE
, LOCATION_DETAIL_TEXT
, LOCATION_TYPE_CODE
, RETURN_DATE
, PROVIDER_ID
, CREATED_BY
, CREATED_DATE
, MODIFIED_BY
, MODIFIED_DATE
, CREATED_IN_ERROR_FLAG
, PAID_LEAVE_DAYS
, PAID_LEAVE_OVERRIDE_COMMENT
, PLACEMENT_TYPE_CODE
, GROUP_CAT_ID
, APP_VERSION_NBR

from openquery(adhoc_sacrpt,'
select 
PLACEMENT_SETTING_ID
, PLACEMENT_LEAVE_ID
, ESTIMATED_RETURN_DATE
, LEAVE_DATE
, LEAVE_TYPE_CODE
, LOCATION_DETAIL_TEXT
, LOCATION_TYPE_CODE
, RETURN_DATE
, PROVIDER_ID
, CREATED_BY
, CREATED_DATE
, MODIFIED_BY
, MODIFIED_DATE
, CREATED_IN_ERROR_FLAG
, PAID_LEAVE_DAYS
, PAID_LEAVE_OVERRIDE_COMMENT
, PLACEMENT_TYPE_CODE
, GROUP_CAT_ID
, APP_VERSION_NBR
from sacwis.Placement_Leave
-- where 
')