use SacwisCuy
go

truncate table Agency_Certification
go

insert into Agency_Certification
select 
AGENCY_CERTIFICATION_ID
, AGENCY_ID
, CERTIFICATION_STATUS_CODE
, APP_TYPE_CODE
, AMENDMENT_REASON_CODE
, AMENDMENT_DESC
, EFFECTIVE_DATE
, EXPIRATION_DATE
, TEMP_EXPIRATION_DATE
, CREATED_BY
, CREATED_DATE
, MODIFIED_BY
, MODIFIED_DATE
, CERTIFYING_ENTITY_CODE
, CLOSED_DATE, CLOSED_REASON_CODE
, OTHER_REASON_TEXT
, CLOSING_COMMENTS
, SOURCE_AGENCY_CERT_ID
, APP_VERSION_NBR

from openquery(adhoc_sacrpt,'
select 
AGENCY_CERTIFICATION_ID
, AGENCY_ID
, CERTIFICATION_STATUS_CODE
, APP_TYPE_CODE
, AMENDMENT_REASON_CODE
, AMENDMENT_DESC
, EFFECTIVE_DATE
, EXPIRATION_DATE
, TEMP_EXPIRATION_DATE
, CREATED_BY
, CREATED_DATE
, MODIFIED_BY
, MODIFIED_DATE
, CERTIFYING_ENTITY_CODE
, CLOSED_DATE, CLOSED_REASON_CODE
, OTHER_REASON_TEXT
, CLOSING_COMMENTS
, SOURCE_AGENCY_CERT_ID
, APP_VERSION_NBR
from sacwis.agency_certification
-- where 
')