use SacwisCuy
go

truncate table Contract
go

insert into Contract
select 
CONTRACT_ID
, AGENCY_ID
, PROVIDER_ID
, CONTRACT_NBR
, VENDOR_NBR
, CONTRACT_TYPE_CODE
, CONTRACT_STATUS_CODE
, CONTRACT_BEGIN_DATE
, CONTRACT_END_DATE
, CONTRACT_AMOUNT
, ENCUMBERED_AMOUNT
, CONTRACT_APPROVAL_DATE
, CONTRACT_ENCUMBERED_DATE
, NOTIFICATION_TYPE_CODE
, NOTIFICATION_CEILING_TYPE_CODE
, COMMENT_TEXT
, CREATED_BY
, CREATED_DATE
, MODIFIED_BY
, MODIFIED_DATE
, ORIG_CONTRACT_BEGIN_DATE
, ORIG_CONTRACT_END_DATE
, ORIG_CONTRACT_AMOUNT
, ORIG_CONTRACT_ID
, PAID_LEAVE_DAYS
, APP_VERSION_NBR

from openquery(adhoc_sacrpt,'
select 
CONTRACT_ID
, AGENCY_ID
, PROVIDER_ID
, CONTRACT_NBR
, VENDOR_NBR
, CONTRACT_TYPE_CODE
, CONTRACT_STATUS_CODE
, CONTRACT_BEGIN_DATE
, CONTRACT_END_DATE
, CONTRACT_AMOUNT
, ENCUMBERED_AMOUNT
, CONTRACT_APPROVAL_DATE
, CONTRACT_ENCUMBERED_DATE
, NOTIFICATION_TYPE_CODE
, NOTIFICATION_CEILING_TYPE_CODE
, COMMENT_TEXT
, CREATED_BY
, CREATED_DATE
, MODIFIED_BY
, MODIFIED_DATE
, ORIG_CONTRACT_BEGIN_DATE
, ORIG_CONTRACT_END_DATE
, ORIG_CONTRACT_AMOUNT
, ORIG_CONTRACT_ID
, PAID_LEAVE_DAYS
, APP_VERSION_NBR
from sacwis.Contract
-- where 
')