use SacwisCuy
go

truncate table Provider_License
go

insert into Provider_License
select 
PROVIDER_ID
, PROVIDER_TYPE_ID
, PROVIDER_LICENSE_ID
, CLOSED_REASON_CODE
, LICENSED_LEVEL_OF_CARE_CODE
, LICENSE_EFFECTIVE_DATE
, LICENSE_EXPIRATION_DATE
, LICENSE_STATUS_CODE
, STATUS_EFFECTIVE_DATE
, PROVIDER_NAME_TEXT
, LICENSED_ADDRESS_ID
, CREATED_BY
, CREATED_DATE
, MODIFIED_BY
, MODIFIED_DATE
, CERTIFYING_ENTITY_CODE
, APP_VERSION_NBR

from openquery(adhoc_sacrpt,'
select
PROVIDER_ID
, PROVIDER_TYPE_ID
, PROVIDER_LICENSE_ID
, CLOSED_REASON_CODE
, LICENSED_LEVEL_OF_CARE_CODE
, LICENSE_EFFECTIVE_DATE
, LICENSE_EXPIRATION_DATE
, LICENSE_STATUS_CODE
, STATUS_EFFECTIVE_DATE
, PROVIDER_NAME_TEXT
, LICENSED_ADDRESS_ID
, CREATED_BY
, CREATED_DATE
, MODIFIED_BY
, MODIFIED_DATE
, CERTIFYING_ENTITY_CODE
, APP_VERSION_NBR

from sacwis.Provider_License
-- where 
')