use SacwisCuy
go

truncate table Service_Type
go

insert into Service_Type
select 
SERVICE_ID
, AGENCY_ID
, SERVICE_DESC
, SERVICE_LONG_DESC
, OBSOLETE_DATE
, UNPAID_SVC_FLAG
, PRE_PAID_PAY_FLAG
, PLACEMENT_SRV_FLAG
, PROSPECTIVE_PAY_FLAG
, GROUP_CAT_ID
, CREATED_BY
, CREATED_DATE
, LEAVE_DAYS_TO_BE_PAID
, MODIFIED_BY
, MODIFIED_DATE
, FUND_SOURCE_DESC
, APP_VERSION_NBR

from openquery(adhoc_sacrpt,'
select
SERVICE_ID
, AGENCY_ID
, SERVICE_DESC
, SERVICE_LONG_DESC
, OBSOLETE_DATE
, UNPAID_SVC_FLAG
, PRE_PAID_PAY_FLAG
, PLACEMENT_SRV_FLAG
, PROSPECTIVE_PAY_FLAG
, GROUP_CAT_ID
, CREATED_BY
, CREATED_DATE
, LEAVE_DAYS_TO_BE_PAID
, MODIFIED_BY
, MODIFIED_DATE
, FUND_SOURCE_DESC
, APP_VERSION_NBR

from sacwis.Service_Type
-- where 
')