use SacwisCuy
go

truncate table Placement_Episode
go

insert into Placement_Episode
select 
LEGAL_STATUS_INFO_ID
, CHILD_ID
, PLACEMENT_EPISODE_ID
, REMOVED_DATE
, REMOVAL_CIRCUMSTANCE_CODE
, RESPONSIBLE_SCHL_DISTRICT_CODE
, CARETAKER_STRUCTURE_CODE
, PRIMARY_CARETAKER_ID
, SECONDARY_CARETAKER_ID
, REMOVAL_REASON_TEXT
, REMOVAL_PREVENTION_EFFORT_TEXT
, REMOVAL_COURT_SUPPORT_TEXT
, DISCHARGE_DATE
, DISCHARGE_REASON_CODE
, STATUS_CODE
, CREATED_BY
, CREATED_DATE
, MODIFIED_BY
, MODIFIED_DATE
, OTHER_SCHL_DISTRICT_NAME
, SYSTEM_DISCHARGE_DATE
, PRIMARY_REMOVAL_REASON_CODE
, AWOL_AT_REMOVAL_FLAG
, REMOVAL_SCHOOL_TEXT
, NOT_OF_SCHOOL_AGE_FLAG
, CHILD_REMAINED_AT_SCHOOL_FLAG
, APP_VERSION_NBR

from openquery(adhoc_sacrpt,'
select 
LEGAL_STATUS_INFO_ID
, CHILD_ID
, PLACEMENT_EPISODE_ID
, REMOVED_DATE
, REMOVAL_CIRCUMSTANCE_CODE
, RESPONSIBLE_SCHL_DISTRICT_CODE
, CARETAKER_STRUCTURE_CODE
, PRIMARY_CARETAKER_ID
, SECONDARY_CARETAKER_ID
, REMOVAL_REASON_TEXT
, REMOVAL_PREVENTION_EFFORT_TEXT
, REMOVAL_COURT_SUPPORT_TEXT
, DISCHARGE_DATE
, DISCHARGE_REASON_CODE
, STATUS_CODE
, CREATED_BY
, CREATED_DATE
, MODIFIED_BY
, MODIFIED_DATE
, OTHER_SCHL_DISTRICT_NAME
, SYSTEM_DISCHARGE_DATE
, PRIMARY_REMOVAL_REASON_CODE
, AWOL_AT_REMOVAL_FLAG
, REMOVAL_SCHOOL_TEXT
, NOT_OF_SCHOOL_AGE_FLAG
, CHILD_REMAINED_AT_SCHOOL_FLAG
, APP_VERSION_NBR
from sacwis.Placement_Episode
-- where 
')