use SacwisCuy
go

truncate table Case_Base
go

insert into Case_Base
select 
CASE_ID
, FIRST_NAME
, MIDDLE_NAME
, LAST_NAME
, PRIMARY_CARETAKER_CODE
, SECONDARY_CARETAKER_CODE
, CLOSED_CASE_ADDRESS_ID
, CREATED_BY
, CREATED_DATE
, MODIFIED_BY
, MODIFIED_DATE
, ISADOPTIONCASE_FLAG
, ORIGINAL_CASE_ID
, RESTRICTED_FLAG
, RESTRICTED_BY_EMPLOYEE_ID
, RESTRICTED_COMMENTS_TEXT
, RESTRICTED_DATE
, APP_VERSION_NBR

from openquery(adhoc_sacrpt,'
select 
CASE_ID
, FIRST_NAME
, MIDDLE_NAME
, LAST_NAME
, PRIMARY_CARETAKER_CODE
, SECONDARY_CARETAKER_CODE
, CLOSED_CASE_ADDRESS_ID
, CREATED_BY
, CREATED_DATE
, MODIFIED_BY
, MODIFIED_DATE
, ISADOPTIONCASE_FLAG
, ORIGINAL_CASE_ID
, RESTRICTED_FLAG
, RESTRICTED_BY_EMPLOYEE_ID
, RESTRICTED_COMMENTS_TEXT
, RESTRICTED_DATE
, APP_VERSION_NBR
from sacwis.Case_Base
-- where 
')