use SacwisCuy
go

truncate table Person
go

insert into Person
select 
PERSON_ID
, PARTY_ID
, PREFIX_CODE
, FIRST_NAME
, MIDDLE_NAME
, LAST_NAME
, SUFFIX_CODE
, GENDER_CODE
, SSN
, BIRTH_DATE
, BIRTH_CITY_NAME
, BIRTH_STATE
, BIRTH_COUNTRY_NAME
, DRIV_LIC_NBR
, DRIV_LIC_EXP_DATE
, DRIV_LIC_ISS_STATE_CODE
, INDIAN_TRIBE1
, INDIAN_TRIBE2
, RELIGION_CODE
, OTHER_RELIGION_DESC
, OTHER_RACE_DESC
, OTHER_ETHNICITY_DESC
, OTHER_LANGUAGE_DESC
, INTERPRETER_FLAG
, DECEASED_FLAG
, DECEASED_DATE
, PREV_ADOPTED_CODE
, AGE_ADOPTED_CODE
, EDUCATION_LEVEL_CODE
, HISPANIC_LATINO_CODE
, OHIO_RESIDENT_FLAG
, ACTV_MILITARY_FLAG
, DEP_ACTV_MILITARY_FLAG
, CRIMINAL_HIST_CODE
, SAFETY_HAZARD_FLAG
, ENV_HAZARD_FLAG
, SAFETY_PLAN_FLAG
, AWOL_FLAG
, MENTAL_HLTH_HAZ_FLAG
, DRUG_ACTVTY_HAZ_FLAG
, CONTAG_DISEASE_HAZ_FLAG
, DOMESTIC_VIOLENCE_HAZ_FLAG
, GANG_ACTVTY_HAZ_FLAG
, PRIOR_WRKR_THREAT_HAZ_FLAG
, VIOLENT_CRIME_HAZ_FLAG
, SEXUAL_PREDATOR_HAZ_FLAG
, EXPLOSIVE_BEHAV_HAZ_FLAG
, PROTECTIVE_SERVICE_ALERT_FLAG
, SAFETY_HAZ_NARRATIVE
, BACKGROUND_CHECK_RCVD_DATE
, BACKGROUND_CHECK_RQSTD_DATE
, CREATED_BY, CREATED_DATE
, MODIFIED_BY, MODIFIED_DATE
, CHAR_NOT_COMPLETED_FLAG
, CHAR_NOT_DISABILITY_FLAG
, ESTIMATED_DOB_FLAG
, WEAPONS_HAZARD_FLAG
, OTHER_HAZARD_FLAG
, INDIAN_TRIBE_RECOGNIZED1
, INDIAN_TRIBE_RECOGNIZED2
, RAPBACK_FLAG
, DECEASED_DATE_UNKNOWN_FLAG
, US_CITIZEN_CODE
, ALIEN_STATUS_CODE
, COUNTRY_OF_ORIGIN_CODE
, US_ENTRY_DATE
, CRISE_SEGMENT_DATE
, VERIFICATION_CODE_1
, UNKNOWN_DOB_FLAG
, MOTHER_MARRIED_AT_DOB_CODE
, SETS_MODIFIED_DATE
, APP_VERSION_NBR

 from openquery(adhoc_sacrpt,'
 select
 PERSON_ID
, PARTY_ID
, PREFIX_CODE
, FIRST_NAME
, MIDDLE_NAME
, LAST_NAME
, SUFFIX_CODE
, GENDER_CODE
, SSN
, BIRTH_DATE
, BIRTH_CITY_NAME
, BIRTH_STATE
, BIRTH_COUNTRY_NAME
, DRIV_LIC_NBR
, DRIV_LIC_EXP_DATE
, DRIV_LIC_ISS_STATE_CODE
, INDIAN_TRIBE1
, INDIAN_TRIBE2
, RELIGION_CODE
, OTHER_RELIGION_DESC
, OTHER_RACE_DESC
, OTHER_ETHNICITY_DESC
, OTHER_LANGUAGE_DESC
, INTERPRETER_FLAG
, DECEASED_FLAG
, DECEASED_DATE
, PREV_ADOPTED_CODE
, AGE_ADOPTED_CODE
, EDUCATION_LEVEL_CODE
, HISPANIC_LATINO_CODE
, OHIO_RESIDENT_FLAG
, ACTV_MILITARY_FLAG
, DEP_ACTV_MILITARY_FLAG
, CRIMINAL_HIST_CODE
, SAFETY_HAZARD_FLAG
, ENV_HAZARD_FLAG
, SAFETY_PLAN_FLAG
, AWOL_FLAG
, MENTAL_HLTH_HAZ_FLAG
, DRUG_ACTVTY_HAZ_FLAG
, CONTAG_DISEASE_HAZ_FLAG
, DOMESTIC_VIOLENCE_HAZ_FLAG
, GANG_ACTVTY_HAZ_FLAG
, PRIOR_WRKR_THREAT_HAZ_FLAG
, VIOLENT_CRIME_HAZ_FLAG
, SEXUAL_PREDATOR_HAZ_FLAG
, EXPLOSIVE_BEHAV_HAZ_FLAG
, PROTECTIVE_SERVICE_ALERT_FLAG
, SAFETY_HAZ_NARRATIVE
, BACKGROUND_CHECK_RCVD_DATE
, BACKGROUND_CHECK_RQSTD_DATE
, CREATED_BY, CREATED_DATE
, MODIFIED_BY, MODIFIED_DATE
, CHAR_NOT_COMPLETED_FLAG
, CHAR_NOT_DISABILITY_FLAG
, ESTIMATED_DOB_FLAG
, WEAPONS_HAZARD_FLAG
, OTHER_HAZARD_FLAG
, INDIAN_TRIBE_RECOGNIZED1
, INDIAN_TRIBE_RECOGNIZED2
, RAPBACK_FLAG
, DECEASED_DATE_UNKNOWN_FLAG
, US_CITIZEN_CODE
, ALIEN_STATUS_CODE
, COUNTRY_OF_ORIGIN_CODE
, US_ENTRY_DATE
, CRISE_SEGMENT_DATE
, VERIFICATION_CODE_1
, UNKNOWN_DOB_FLAG
, MOTHER_MARRIED_AT_DOB_CODE
, SETS_MODIFIED_DATE
, APP_VERSION_NBR
from Sacwis.Person
')