use SacwisCuy
go

truncate table Case_Status
go

insert into Case_Status
select 
CASE_STATUS_ID
, CASE_ID
, CASE_STATUS_CODE
, BEGIN_EFF_DATE
, END_EFF_DATE
, CREATED_BY
, CREATED_DATE
, MODIFIED_BY
, MODIFIED_DATE
, SUNSET_DATE
, SUNSET_ACTIVITY_CODE
, APP_VERSION_NBR

from openquery(adhoc_sacrpt,'
select 
CASE_STATUS_ID
, CASE_ID
, CASE_STATUS_CODE
, BEGIN_EFF_DATE
, END_EFF_DATE
, CREATED_BY
, CREATED_DATE
, MODIFIED_BY
, MODIFIED_DATE
, SUNSET_DATE
, SUNSET_ACTIVITY_CODE
, APP_VERSION_NBR
from sacwis.Case_Status
-- where 
')