:r S:\IS\ETL\SACWIS\RevisedNightlyDownloadProcess\ETL_NewSqlSvr\PartialLoads\PartialLoadAddress.sql
:r S:\IS\ETL\SACWIS\RevisedNightlyDownloadProcess\ETL_NewSqlSvr\PartialLoads\PartialLoadAgency.sql
:r S:\IS\ETL\SACWIS\RevisedNightlyDownloadProcess\ETL_NewSqlSvr\PartialLoads\PartialLoadAgencyCertProviderLink.sql
:r S:\IS\ETL\SACWIS\RevisedNightlyDownloadProcess\ETL_NewSqlSvr\PartialLoads\PartialLoadAgencyCertification.sql
:r S:\IS\ETL\SACWIS\RevisedNightlyDownloadProcess\ETL_NewSqlSvr\PartialLoads\PartialLoadCaseAgencyLink.sql
:r S:\IS\ETL\SACWIS\RevisedNightlyDownloadProcess\ETL_NewSqlSvr\PartialLoads\PartialLoadCaseBase.sql
:r S:\IS\ETL\SACWIS\RevisedNightlyDownloadProcess\ETL_NewSqlSvr\PartialLoads\PartialLoadCaseCategory.sql
:r S:\IS\ETL\SACWIS\RevisedNightlyDownloadProcess\ETL_NewSqlSvr\PartialLoads\PartialLoadCaseParticipant.sql
:r S:\IS\ETL\SACWIS\RevisedNightlyDownloadProcess\ETL_NewSqlSvr\PartialLoads\PartialLoadCaseParticipantReln.sql
:r S:\IS\ETL\SACWIS\RevisedNightlyDownloadProcess\ETL_NewSqlSvr\PartialLoads\PartialLoadCaseParticipantStatus.sql
:r S:\IS\ETL\SACWIS\RevisedNightlyDownloadProcess\ETL_NewSqlSvr\PartialLoads\PartialLoadCaseStatus.sql
:r S:\IS\ETL\SACWIS\RevisedNightlyDownloadProcess\ETL_NewSqlSvr\PartialLoads\PartialLoadContract.sql
:r S:\IS\ETL\SACWIS\RevisedNightlyDownloadProcess\ETL_NewSqlSvr\PartialLoads\PartialLoadPartyAddress.sql
:r S:\IS\ETL\SACWIS\RevisedNightlyDownloadProcess\ETL_NewSqlSvr\PartialLoads\PartialLoadPerson.sql
:r S:\IS\ETL\SACWIS\RevisedNightlyDownloadProcess\ETL_NewSqlSvr\PartialLoads\PartialLoadPlacementEpisode.sql
:r S:\IS\ETL\SACWIS\RevisedNightlyDownloadProcess\ETL_NewSqlSvr\PartialLoads\PartialLoadPlacementLeave.sql
:r S:\IS\ETL\SACWIS\RevisedNightlyDownloadProcess\ETL_NewSqlSvr\PartialLoads\PartialLoadPlacementSetting.sql
:r S:\IS\ETL\SACWIS\RevisedNightlyDownloadProcess\ETL_NewSqlSvr\PartialLoads\PartialLoadProvider.sql
:r S:\IS\ETL\SACWIS\RevisedNightlyDownloadProcess\ETL_NewSqlSvr\PartialLoads\PartialLoadProviderCharDetail.sql
:r S:\IS\ETL\SACWIS\RevisedNightlyDownloadProcess\ETL_NewSqlSvr\PartialLoads\PartialLoadProviderCharacteristics.sql
:r S:\IS\ETL\SACWIS\RevisedNightlyDownloadProcess\ETL_NewSqlSvr\PartialLoads\PartialLoadProviderLicense.sql
:r S:\IS\ETL\SACWIS\RevisedNightlyDownloadProcess\ETL_NewSqlSvr\PartialLoads\PartialLoadProviderName.sql
:r S:\IS\ETL\SACWIS\RevisedNightlyDownloadProcess\ETL_NewSqlSvr\PartialLoads\PartialLoadProviderPlacementCriteria.sql
:r S:\IS\ETL\SACWIS\RevisedNightlyDownloadProcess\ETL_NewSqlSvr\PartialLoads\PartialLoadProviderStatus.sql
:r S:\IS\ETL\SACWIS\RevisedNightlyDownloadProcess\ETL_NewSqlSvr\PartialLoads\PartialLoadProviderType.sql
:r S:\IS\ETL\SACWIS\RevisedNightlyDownloadProcess\ETL_NewSqlSvr\PartialLoads\PartialLoadPrvdrPlcmntCriteriaDetail.sql
:r S:\IS\ETL\SACWIS\RevisedNightlyDownloadProcess\ETL_NewSqlSvr\PartialLoads\PartialLoadRace.sql
:r S:\IS\ETL\SACWIS\RevisedNightlyDownloadProcess\ETL_NewSqlSvr\PartialLoads\PartialLoadRefData.sql
:r S:\IS\ETL\SACWIS\RevisedNightlyDownloadProcess\ETL_NewSqlSvr\PartialLoads\PartialLoadServiceType.sql