CREATE TABLE [Staging].[Cases]
(
	[CaseKey] INT IDENTITY(1,1) NOT NULL,
	[SysInsertUser] VARCHAR(50) NOT NULL DEFAULT 'System',
	[SysInsertDate] DATETIME NOT NULL DEFAULT getdate(),

	[AbleToCareForThemselves] [varchar](7) NULL,
	[AbleToCareForThemselvesInformation] [varchar](max) NULL,
	[ActionsTakenPriorToThisCall] [bit] NULL,
	[AdditionalNotes] [varchar](max) NULL,
	[AdequateNutritionHydration] [bit] NOT NULL,
	[AdequateSupervision] [bit] NULL,
	[ADLsToiletingBathingHygieneToileting] [bit] NULL,
	[AgenciesAssistingInInvestigation] [varchar](7) NULL,
	[AllowSomeoneToLiveWithThem] [bit] NULL,
	[AppropriateMedicalTreatment] [bit] NULL,
	[ApprovalKickoff] [bit] NULL,
	[ApprovalStatus] [varchar](50) NULL,
	[ApproximateAge] [decimal](18, 2) NULL,
	[ApproximatLossOfAssets] [money] NULL,
	[APTeamReviewDate] [date] NULL,
	[AreThereExistingConditions] [varchar](7) NULL,
	[AreThereSafetyIssuesForCO] [varchar](8000) NULL,
	[ReAssessmentCompletedDate] [date] NULL,
	[AssessmentCount] [decimal](18, 0) NULL,
	[AssessmentScoringInfo] [varchar](8000) NULL,
	[AuxiliaryDate] [date] NULL,
	[FirstAssessmentRiskScore] [decimal](3, 2) NULL,
	[FirstAssessmentSafetyScore] [decimal](3, 2) NULL,
	[BathingAndHygiene] [bit] NULL,
	[BestTimeToReachClient] [varchar](255) NULL,
	[BillsFinances] [bit] NULL,
	[Biohazard] [bit] NULL,
	[PhysicalAbuseBrokenBones] [bit] NULL,
	[SexualAbuseBrokenBones] [bit] NULL,
	[PhysicalAbuseBruises] [bit] NULL,
	[SexualAbuseBruises] [bit] NULL,
	[BugOrVerminInfestation] [bit] NULL,
	[CaretakerAdditionalDetails] [varchar](8000) NULL,
	[CaretakerNeglect] [bit] NULL,
	[CaretakerNeglectWereThereAnyWitness] [varchar](7) NULL,
	[CaseClosureApprovalStatus] [varchar](50) NULL,
	[CaseClosureCorrectionsCompleted] [bit] NULL,
	[OnGoingClientNeeds] [varchar](max) NULL,
	[CaseDuration] [decimal](18, 0) NULL,
	[Name] [varchar](80) NULL,
	[CasePlanCompletedDate] [date] NULL,
	[CasePlanCount] [decimal](18, 0) NULL,
	[CauseHarmOrLoss] [varchar](7) NULL,
	[CauseHarmOrLossInformation] [varchar](max) NULL,
	[CBMSCaseNumber] [varchar](20) NULL,
	[ClientAddress] [varchar](8000) NULL,
	[ClientAllegedPerpetratorHistory] [varchar](8000) NULL,
	[ClientAtRiskInfo] [varchar](5000) NULL,
	[ClientName] [varchar](50) NULL,
	[ClientsAge] [decimal](18, 0) NULL,
	[ClientsCurrentLocation] [varchar](50) NULL,
	[CaseClosedReason] [varchar](8000) NULL,
	[ComplicatingRisksVulnerabilities] [varchar](8000) NULL,
	[ConditionNone] [bit] NULL,
	[ConditionRequiringTotalPhysicalCare] [bit] NULL,
	[ConditionUnabletoManageNone] [bit] NULL,
	[ConditionUnabletoManageUnknown] [bit] NULL,
	[ConditionUnknown] [bit] NULL,
	[Confidential] [bit] NULL,
	[TemporaryContact] [varchar](50) NULL,
	[ContagiousDisease] [bit] NULL,
	[CountOfAllegations] [decimal](18, 0) NULL,
	[CaseCounty] [varchar](8000) NULL,
	[CountyCalendar] [varchar](255) NULL,
	[CountyHeld] [varchar](8000) NULL,
	[CountyTypeOfAuthority] [varchar](8000) NULL,
	[CourtReportCompletedDate] [date] NULL,
	[CourtReportDueDate] [date] NULL,
	[CreatedById] [varchar](18) NULL,
	[CreatedDate] [date] NULL,
	[CriminalInvestigationStatus] [varchar](50) NULL,
	[CulturalConsiderations] [varchar](8000) NULL,
	[CurrentStrengthsSupports] [varchar](max) NULL,
	[PhysicalAbuseCuts] [bit] NULL,
	[SexualAbuseCuts] [bit] NULL,
	[DangerHarm] [varchar](8000) NULL,
	[DangerousAggressiveAnimals] [bit] NULL,
	[DangerousHomeStructure] [bit] NULL,
	[DateCaseClosed] [date] NULL,
	[DateOfBirth] [date] NULL,
	[DateOfDeath] [date] NULL,
	[DaysBetweenAssessments] [decimal](18, 10) NULL,
	[DaysOfInActivity] [decimal](18, 0) NULL,
	[DaysOpen] [decimal](18, 0) NULL,
	[DecisionMakingUnderstandingDeficits] [bit] NULL,
	[DeclineInAbilities] [varchar](7) NULL,
	[DeclineInAbilitiesInformation] [varchar](max) NULL,
	[IsDeleted] [bit] NULL,
	[DementiaAlzheimers] [bit] NULL,
	[DevelopmentalIntellectualDisability] [bit] NULL,
	[DiagnosedMentalIllness] [varchar](7) NULL,
	[DiagnosedMentalIllnessInfo] [varchar](max) NULL,
	[DifferenceOfDays] [decimal](18, 0) NULL,
	[DocumentsForLegalAuthority] [varchar](7) NULL,
	[DoesAdultHaveSupportHelpInPlace] [varchar](7) NULL,
	[DoesAllegedPerpHaveAccessToAdult] [varchar](7) NULL,
	[DoesPerpHoldLegalAuthority] [varchar](7) NULL,
	[DoesPerpLiveWithClient] [varchar](7) NULL,
	[DoesPartyReceiveFundsFromClient] [varchar](7) NULL,
	[EmergencyImmediateHarm] [bit] NULL,
	[EmergencyImmediateHarmInformation] [varchar](max) NULL,
	[EvidenceOfNeglectExploitationAndA] [varchar](max) NULL,
	[ExplainWhyAdultIsBeingMistreated] [varchar](max) NULL,
	[Exploitation] [bit] NULL,
	[ExploitationAdditionalDetails] [varchar](8000) NULL,
	[FearAsAResultOfAPersonsAction] [bit] NULL,
	[FirearmsOrOtherWeapons] [bit] NULL,
	[ForAnotherPersonsNeeds] [bit] NULL,
	[ForIllegalActivity] [bit] NULL,
	[ForThingsAdultWouldNotPurchase] [bit] NULL,
	[FrailElderly] [bit] NULL,
	[GatedLockedCommunityBuilding] [bit] NULL,
	[GenderCode] [varchar](8000) NULL,
	[GiveAwayMoneyOrProperty] [bit] NULL,
	[GrayAreas] [varchar](8000) NULL,
	[GuardianOrConservatorInPlace] [bit] NULL,
	[HarassesTheAdultInASexualManner] [bit] NULL,
	[HasTheConditionBeenDiagnosed] [varchar](7) NULL,
	[HasThereBeenARecentChange] [varchar](7) NULL,
	[HaveSelfInjuriousBehavior] [bit] NULL,
	[HealthcareMedicalNeeds] [bit] NULL,
	[HelpFromFamilyFriendsOthers] [bit] NULL,
	[HoardingIncludingAnimals] [bit] NULL,
	[HoardingOrAnimalHoarding] [bit] NULL,
	[IADLsCeaningLaundryCooking] [bit] NULL,
	[IllegalActivityInTheHome] [bit] NULL,
	[IllegalDrugManufacturing] [bit] NULL,
	[IllegalDrugUse] [bit] NULL,
	[ImminentForeclosuresOrEviction] [bit] NULL,
	[ImpactAbilityToCommunicate] [bit] NULL,
	[InappropriateConfinement] [bit] NULL,
	[InappropriateRestraint] [bit] NULL,
	[InappropriateSexualBehaviors] [bit] NULL,
	[InitialAssessmentCompleteDate] [date] NULL,
	[InitialAssessmentDueDate] [date] NULL,
	[InitialCasePlanCompleteDate] [date] NULL,
	[InitialCasePlanDueDate] [date] NULL,
	[InitialResponseDate] [date] NULL,
	[InitialResponseDueDate] [date] NULL,
	[InitialResponseType] [varchar](50) NULL,
	[InProgressCasePlans] [decimal](18, 0) NULL,
	[Interviews] [varchar](max) NULL,
	[InvestigationApprovalStatus] [varchar](50) NULL,
	[InvestigationCompletedDate] [date] NULL,
	[InvestigationDueDate] [date] NULL,
	[InWhatCapacityCoesPerpHaveAccess] [varchar](8000) NULL,
	[IsThereAWillOrPowerOfAttorney] [varchar](7) NULL,
	[IsThisARecentChangeInBehavior] [varchar](7) NULL,
	[KnownCriminalActivityHistory] [bit] NULL,
	[KnownGangActivity] [bit] NULL,
	[LackOfAccessPathways] [bit] NULL,
	[LastActivityChildObjects] [date] NULL,
	[LastActivityDate] [date] NULL,
	[LastModifiedById] [varchar](18) NOT NULL,
	[LastModifiedDate] [date] NOT NULL,
	[LastMonthlyContactDate] [date] NULL,
	[LastReferencedDate] [datetime] NULL,
	[LastViewedDate] [datetime] NULL,
	[LawEnforcementRequestedByAPS] [varchar](7) NULL,
	[MajorMentalIllnessEmotionalDisorder] [bit] NULL,
	[MakeChangesToABankAccount] [bit] NULL,
	[MakesSexualInnuendosTowardTheAdult] [bit] NULL,
	[MakesTheAdultPerformSexualActs] [bit] NULL,
	[MakesTheAdultWatchPornography] [bit] NULL,
	[MalnutritionSuddenWeightLossGain] [bit] NULL,
	[ManagingHomeCleanliness] [bit] NULL,
	[MaritalStatusCode] [varchar](50) NULL,
	[MedicalConditions] [bit] NULL,
	[MedicallyFragile] [bit] NULL,
	[MedicationManagement] [bit] NULL,
	[MemoryDecisionMakingProblems] [varchar](7) NULL,
	[MemoryDecisionMakingProblemsInfo] [varchar](max) NULL,
	[MemoryDeficits] [bit] NULL,
	[MemoryProblems] [bit] NULL,
	[MentalIllness] [bit] NULL,
	[MismanagementOfMedications] [bit] NULL,
	[MistreatmentCategory] [varchar](255) NULL,
	[MonthlyContactDueDate] [date] NULL,
	[NAMRSClientAge] [varchar](5000) NULL,
	[NeurologicalImpairmentStrokeTBIMS] [bit] NULL,
	[NewScreeninOutRecommendatio] [varchar](8000) NULL,
	[NextCasePlanDueDate] [date] NULL,
	[NoAtRiskIssues] [bit] NULL,
	[NoMistreatment] [bit] NULL,
	[Nonworkingappliances] [bit] NULL,
	[NonworkingUtilities] [bit] NULL,
	[NoPhysicalMedicalCondition] [bit] NULL,
	[OfCasePlans] [decimal](18, 0) NULL,
	[XOfCases] [decimal](16, 2) NULL,
	[XOfIntakes] [decimal](16, 2) NULL,
	[XOFMonthlyContacts] [decimal](18, 0) NULL,
	[OfNotYetImplementedClientServices] [decimal](18, 0) NULL,
	[OfOpenAllegations] [decimal](18, 0) NULL,
	[OfOpenPerpFindings] [decimal](18, 0) NULL,
	[OfSubstantiatedAllegations] [decimal](18, 0) NULL,
	[OngoingAllegedPerpetratorInvolvement] [varchar](7) NULL,
	[OngoingPerpetratorInvolvement] [varchar](max) NULL,
	[OtherInvolvedParties] [varchar](max) NULL,
	[OwnerId] [varchar](18) NULL,
	[OwnerProfile] [varchar](8000) NULL,
	[PainAsAResultOfAPersonsActions] [bit] NULL,
	[PerpLegalAuthorityType] [varchar](50) NULL,
	[PhysicalAbuse] [bit] NULL,
	[PhysicalAbuseAdditionalDetails] [varchar](8000) NULL,
	[PhysicalAbuseWereThereAnyWitnesses] [varchar](7) NULL,
	[PhysicalConditions] [bit] NULL,
	[PhysicalImpairment] [bit] NULL,
	[PhysicalMedicalAdditionalDetails] [varchar](8000) NULL,
	[PhysicalMedicalConditions] [varchar](7) NULL,
	[PhysicalMedicalConditionsInformation] [varchar](max) NULL,
	[POAInPlace] [bit] NULL,
	[PoliceFrequentlyCalledInToTheHome] [bit] NULL,
	[PoorHygieneNotBathing] [bit] NULL,
	[PreviousAssessmentCompletedDate] [date] NULL,
	[PreviousMonthlyContact] [date] NULL,
	[PrimaryLanguageCode] [varchar](20) NULL,
	[ProfessionalServicesInPlace] [bit] NULL,
	[QuestionableTransferOfMoneyProperty] [bit] NULL,
	[ReadyToCloseCase] [bit] NULL,
	[ReAssessmentDueDate] [date] NULL,
	[LastAssessmentRiskScore] [decimal](3, 2) NULL,
	[LastAssessmentSafetyScore] [decimal](3, 2) NULL,
	[CaseID] [varchar](18) NOT NULL,
	[RecordTypeID] [varchar](18) NOT NULL,
	[RefusesRecommendedServices] [bit] NULL,
	[ReportingPartyRelationshipRole] [varchar](255) NULL,
	[ReportingPartyRelationshipToClient] [varchar](50) NULL,
	[MandatedReport] [varchar](7) NULL,
	[ReportCameFromLawEnforcement] [varchar](7) NULL,
	[ReportingPartyName] [varchar](80) NULL,
	[ReportingPartyRelationshipNotes] [varchar](50) NULL,
	[RepPayeeInPlace] [bit] NULL,
	[ResponseDueDate] [date] NULL,
	[ResponseExplanation] [varchar](255) NULL,
	[ReviewedByAPTeam_REF] [varchar](18) NULL,
	[RiskScoreDifference] [decimal](18, 0) NULL,
	[RiskScoreOutcome] [decimal](18, 2) NULL,
	[SafetyImprovementPercentage] [decimal](18, 2) NULL,
	[SafetyPerception] [decimal](18, 0) NULL,
	[SafetyScoreDifference] [decimal](18, 0) NULL,
	[SafetyScoreOutcome] [decimal](18, 2) NULL,
	[SafetyWarning] [varchar](8000) NULL,
	[ScorecardReview] [bit] NULL,
	[PhysicalAbuseScratches] [bit] NULL,
	[SexualAbuseScratches] [bit] NULL,
	[ScreenInScreenOutRecommendation] [varchar](8000) NULL,
	[ScreenInOutSummary] [varchar](8000) NULL,
	[ScreenOutReason] [varchar](255) NULL,
	[SecuritySystemCameras] [bit] NULL,
	[SelfNeglect] [bit] NULL,
	[SelfNeglectAdditionalDetails] [varchar](8000) NULL,
	[SexualAbuse] [bit] NULL,
	[SexualAbuseAdditionalDetails] [varchar](8000) NULL,
	[SexualAbuseWereThereAnywitnesses] [varchar](7) NULL,
	[SignAQuitClaimDeed] [bit] NULL,
	[SocialInteractionFamilyFriendsVisit] [bit] NULL,
	[SpecifyIFNo] [varchar](max) NULL,
	[CaseClosedAdditionalInformation] [varchar](max) NULL,
	[SpecifyOtherCurrentLocation] [varchar](255) NULL,
	[SpecifyOtherRelationship] [varchar](255) NULL,
	[SpecifyOtherScreenOutReason] [varchar](50) NULL,
	[SpecifyWhyNoAssistanceWasReceived] [varchar](max) NULL,
	[Status] [varchar](50) NULL,
	[SubstanceAbuse] [bit] NULL,
	[SelfNeglectSubstanceAbuse] [bit] NULL,
	[SubstanceAbuseIncludingRXmeds] [bit] NULL,
	[SubstantiatedExploitation] [decimal](18, 0) NULL,
	[SumOfCountyFundsUsed] [money] NULL,
	[Supervisor_REF] [varchar](18) NULL,
	[SupervisorEmail] [varchar](255) NULL,
	[SupervisorName] [varchar](8000) NULL,
	[SupportNetworkLivesWithClient] [varchar](7) NULL,
	[SupportNetworkNarrative] [varchar](5000) NULL,
	[SystemModStamp] [datetime] NOT NULL,
	[TeamMembers] [varchar](5000) NULL,
	[TimelyInitialAssessment] [varchar](5000) NULL,
	[TimelyInitialCasePlan] [varchar](5000) NULL,
	[LateInitialResponse] [varchar](5000) NULL,
	[TimelyInvestigation] [varchar](5000) NULL,
	[TimelyMonthlyContact] [varchar](5000) NULL,
	[ToDoAnythingTheyWouldntDoNormally] [bit] NULL,
	[Transportation] [bit] NULL,
	[UnableToCareForThemselves] [varchar](7) NULL,
	[UnableToCareForThemselvesInfo] [varchar](max) NULL,
	[UnableToProtectThemselvesCheckbox] [bit] NULL,
	[UnableToProtectThemselves] [varchar](7) NULL,
	[UnableToProtectThemselvesInformation] [varchar](max) NULL,
	[UnexplainedLossOfMoneyProperty] [bit] NULL,
	[UnknownAtRiskPopulation] [bit] NULL,
	[MinorImpacts] [varchar](max) NULL,
	[SignificantImpacts] [varchar](max) NULL,
	[UnpaidUtilities] [bit] NULL,
	[UnsafeNeighborhood] [bit] NULL,
	[UnsafStructure] [bit] NULL,
	[UntreatedMedicialCondition] [bit] NULL,
	[UntreatedMentalHealthNeed] [bit] NULL,
	[UntreatedMentalIllness] [bit] NULL,
	[VerminPestInfestation] [bit] NULL,
	[PhysicalAbuseVisibleMarks] [bit] NULL,
	[SexualAbuseVisibleMarks] [bit] NULL,
	[Wander] [bit] NULL,
	[WasAssistanceReceived] [varchar](7) NULL,
	[WhatAreTheDetailsofTheConditions] [varchar](8000) NULL,
	[WhatIsTheConcerYouWantToReport] [varchar](8000) NULL,
	[WhyDidTheReportingPartyCall] [varchar](max) NULL,
	[WhatWouldBeHelpfulToImproeSituation] [varchar](5000) NULL,
	[WhoIsResponsibleForAdultsCare] [varchar](5000) NULL,
	[WithoutAdultsKnowledgePermission] [bit] NULL,
	[SafetyNotes] [varchar](5000) NULL,
	[WorkerSafet_Concerns] [varchar](5000) NULL,
	[WorkerSafetyIssues] [bit] NULL,
	[WorkerSafetyIssuesDesc] [varchar](5000) NULL,

	CONSTRAINT [PK_Cases] PRIMARY KEY CLUSTERED ([CaseKey] ASC)

);
